services:
  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - backend
    ports:
      - '80:80'
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      APP_PORT: ${APP_PORT}
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    ports:
      - '3000:3000'
    depends_on:
      - db
      - keycloak
    networks:
      - app-network

  db:
    image: postgres:16.3
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.5
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    command: start-dev
    ports:
      - '8080:8080'
    volumes:
      - keycloak_data:/opt/keycloak/data
    networks:
      - app-network

  adminer:
    image: adminer
    ports:
      - '8090:8080'
    depends_on:
      - db
    networks:
      - app-network

volumes:
  postgres_data:
  keycloak_data:
  node_modules:

networks:
  app-network:
    driver: bridge
